[workspace]
members = [
	"phira-mp-common",
	"phira-mp-client",
	"phira-mp-macros",
	"phira-mp-server",
]
resolver = "2"

[profile.release]
opt-level = 2
strip = true

[profile.dev.package."*"]
opt-level = 2
