[package]
name = "phira-mp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
phira-mp-common = { path = "../phira-mp-common" }
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
tap = "1.0.1"
tokio = "*"
tracing = "0.1.37"
uuid = { version = "1.3.3", features = ["v4"] }

tracing-appender = "0.2.2"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
rand = "0.8.5"
